package pl.michalkowol.people

internal class NameException(val msg: String) : RuntimeException(msg)
